name: Production CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: simple-backend

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest   

    steps:
      # 1 Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4   

      # 2 Setup Node.js for tests/lint
      - name: Setup Node.js
        uses: actions/setup-node@v4   
        with:
          node-version: '18'

      # 3 Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4 Run tests
      - name: Run tests
        run: npm test

    #   # 5 Run linting
    #   - name: Run linting
    #     run: npm run lint

      # 6 Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 7 Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)  
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:$TAG .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}:$TAG
       
      
          