name: Production CI/CD Pipeline

on:
  push:
    branches: [ main ]   

env:
  DOCKER_IMAGE: simple-backend

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest   

    steps:
      # 1 Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4   

      # 2 Setup Node.js for tests/lint
      - name: Setup Node.js
        uses: actions/setup-node@v4   
        with:
          node-version: '18'

      # 3 Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4 Run tests
      - name: Run tests
        run: npm test

      # 5 Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 6 Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          TAG=$(echo $GITHUB_SHA | head -c7)
          IMAGE=${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_IMAGE }}
          
          # Build Docker image with SHA tag
          docker build -t $IMAGE:$TAG .
          docker push $IMAGE:$TAG

      # 7 SSH and deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        env:
            DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
            TAG: ${{ github.sha }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE_NAME=$DOCKER_HUB_USERNAME/simple-backend
            SHORT_TAG=$(echo $TAG | cut -c1-7)   

            echo "Pulling new Docker image..."
            docker pull $IMAGE_NAME:$SHORT_TAG

            echo "Stopping old container..."
            docker stop simple-backend || true
            docker rm simple-backend || true

            echo "Running new container..."
            docker run -d --name simple-backend -p 3000:3000 $IMAGE_NAME:$SHORT_TAG

            # Health check
            sleep 10
            if curl -f http://localhost:3000/health; then
              echo "Deployment successful"
            else
              echo "Deployment failed!"
            fi
